Broken endpoints UX changes
digital-land/submit pull request #738
Opened 2024-12-12 15:37 UTC by rosado

## What type of PR is this? (check all applicable)

- [x] Refactor
- [x] Feature

## Description

Changes how/where endpoints are displayed.

- The dataset overview page highlights endpoints with 'Error' status and provides links to the endpoint error page.
- The dataset task list now includes an item for each 'Error'-ing endpoint
- The task count includes the 'Error'-ing endpoint
- the `latest_200_date` template param no longer includes the time - it made no sense
- updated the middleware chain for dataset task list to no longer conditionally include the endpoint error page
- made logging in `extractJsonFieldFromEntities` less noisy

## Related Tickets & Documents

- Closes #669 
- Related #670

## QA Instructions, Screenshots, Recordings

TODO

### Before

_Before screenshot here_

### After

_After screenshot here_

## Added/updated tests?
_We encourage you to keep the code coverage percentage at 80% and above._

- [x] Yes

## QA sign off
- [ ] Code has been checked and approved
- [ ] Design has been checked and approved
- [ ] Product and business logic has been checked and proved

2024-12-16 09:52 UTC, DilwoarH requested changes

2024-12-16 09:52 UTC, DilwoarH commented on src/middleware/common.middleware.js
> +    // resource: v.string()
why is this commented out? If we don't need it, just remove it.

2024-12-18 10:11 UTC, DilwoarH reviewed
The code looks good - has @CharliePatterson signed off?

2025-01-03 14:46 UTC, GeorgeGoodall-GovUk submitted a review, later dismissed
looks good

2025-01-09 16:25 UTC, CharliePatterson commented
LGTM @rosado 🙌

2025-01-09 16:34 UTC, merged